services:
  pfm-ml-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pfm-ml-api
    environment:
      - MODEL_PATH=/app/model.pkl
      - PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
